### ISSUE TITLE
Crash when extending or overriding a non-existing rule

### ISSUE THREAD

**Issue by Wenger** [cdglabs/ohm#150]
When writing a rule such as:
`NotARule += New`
or 
`NotARule := New`

If NotARule does not exist, ohm crashes with this error:
```
node_modules/ohm-js/src/errors.js:16
    e = new Error(optInterval.getLineAndColumnMessage() + message);
                              ^

TypeError: optInterval.getLineAndColumnMessage is not a function
    at createError (node_modules/ohm-js/src/errors.js:16:31)
    at Object.cannotExtendUndeclaredRule (node_modules/ohm-js/src/errors.js:81:10)
    at GrammarDecl.extend (node_modules/ohm-js/src/GrammarDecl.js:171:18)
    at metaGrammar.createSemantics.addOperation.Rule_extend (node_modules/ohm-js/src/main.js:133:22)
    at Operation.doAction (node_modules/ohm-js/src/Semantics.js:651:16)
    at Operation.execute (node_modules/ohm-js/src/Semantics.js:627:17)
    at doIt [as visit] (node_modules/ohm-js/src/Semantics.js:412:25)
    at .<anonymous> (node_modules/ohm-js/src/Semantics.js:349:19)
    at Operation.doAction (node_modules/ohm-js/src/Semantics.js:650:16)
    at Operation.execute (node_modules/ohm-js/src/Semantics.js:641:15)
```

It would be helpful if ohm could display that NotARule does not exist

**Comment by pdubroy** [comment]
Thanks for reporting this. This bug was introduced by a recent refactoring of mine, and we didn't catch it due to a bug in our tests :-)
